FROM python:3.12

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN mkdir /app

WORKDIR /app

COPY requirements.txt /app

RUN python -m pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . /app

ENV PATH="/env/script:$PATH" 

RUN python -m venv /env

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
