# Generated by Django 5.1.2 on 2025-01-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
