# Generated by Django 5.1.2 on 2025-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_blog', '0002_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='author',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
